services:
  - type: web
    name: app_provas
    env: ruby
    plan: free
    buildCommand: bundle install && bundle exec rake assets:precompile
    startCommand: ./bin/render-build.sh
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: app_provas_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production

databases:
  - name: app_provas_db
    databaseName: app_provas_production
    plan: free
    region: ohio
